# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dev.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 770)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 50, 1280, 720))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 101, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.camera_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.camera_button_2.setEnabled(True)
        self.camera_button_2.setAutoFillBackground(False)
        self.camera_button_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/kirins/icon/system/RGB_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/kirins/icon/system/thermal_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.camera_button_2.setIcon(icon)
        self.camera_button_2.setIconSize(QtCore.QSize(50, 50))
        self.camera_button_2.setCheckable(True)
        self.camera_button_2.setChecked(False)
        self.camera_button_2.setFlat(True)
        self.camera_button_2.setObjectName("camera_button_2")
        self.verticalLayout_7.addWidget(self.camera_button_2, 0, QtCore.Qt.AlignLeft)
        self.dual_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.dual_button_2.setEnabled(True)
        self.dual_button_2.setAutoFillBackground(False)
        self.dual_button_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/kirins/icon/system/dual.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/kirins/icon/system/dual_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.dual_button_2.setIcon(icon1)
        self.dual_button_2.setIconSize(QtCore.QSize(50, 50))
        self.dual_button_2.setCheckable(True)
        self.dual_button_2.setChecked(False)
        self.dual_button_2.setFlat(True)
        self.dual_button_2.setObjectName("dual_button_2")
        self.verticalLayout_7.addWidget(self.dual_button_2, 0, QtCore.Qt.AlignLeft)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 570, 1261, 142))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.RNG_value_2 = QtWidgets.QLabel(self.layoutWidget)
        self.RNG_value_2.setObjectName("RNG_value_2")
        self.gridLayout_7.addWidget(self.RNG_value_2, 1, 1, 1, 1)
        self.LON_value_2 = QtWidgets.QLabel(self.layoutWidget)
        self.LON_value_2.setObjectName("LON_value_2")
        self.gridLayout_7.addWidget(self.LON_value_2, 2, 2, 1, 2)
        self.ASL_2 = QtWidgets.QLabel(self.layoutWidget)
        self.ASL_2.setObjectName("ASL_2")
        self.gridLayout_7.addWidget(self.ASL_2, 1, 2, 1, 1)
        self.RNG_2 = QtWidgets.QLabel(self.layoutWidget)
        self.RNG_2.setObjectName("RNG_2")
        self.gridLayout_7.addWidget(self.RNG_2, 1, 0, 1, 1)
        self.ASL_value_2 = QtWidgets.QLabel(self.layoutWidget)
        self.ASL_value_2.setObjectName("ASL_value_2")
        self.gridLayout_7.addWidget(self.ASL_value_2, 1, 3, 1, 1)
        self.LAT_value_2 = QtWidgets.QLabel(self.layoutWidget)
        self.LAT_value_2.setObjectName("LAT_value_2")
        self.gridLayout_7.addWidget(self.LAT_value_2, 2, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 0, 0, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.audio_button_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.audio_button_2.setEnabled(True)
        self.audio_button_2.setAutoFillBackground(False)
        self.audio_button_2.setStyleSheet("background-color: transparent;")
        self.audio_button_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/kirins/icon/system/audio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/kirins/icon/system/audio_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.audio_button_2.setIcon(icon2)
        self.audio_button_2.setIconSize(QtCore.QSize(50, 50))
        self.audio_button_2.setCheckable(True)
        self.audio_button_2.setChecked(False)
        self.audio_button_2.setFlat(True)
        self.audio_button_2.setObjectName("audio_button_2")
        self.horizontalLayout_10.addWidget(self.audio_button_2, 0, QtCore.Qt.AlignBottom)
        self.mount_button_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.mount_button_2.setEnabled(True)
        self.mount_button_2.setAutoFillBackground(False)
        self.mount_button_2.setStyleSheet("background-color: transparent;")
        self.mount_button_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/kirins/icon/system/mount.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/kirins/icon/system/mount_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.mount_button_2.setIcon(icon3)
        self.mount_button_2.setIconSize(QtCore.QSize(50, 50))
        self.mount_button_2.setCheckable(True)
        self.mount_button_2.setChecked(False)
        self.mount_button_2.setFlat(True)
        self.mount_button_2.setObjectName("mount_button_2")
        self.horizontalLayout_10.addWidget(self.mount_button_2, 0, QtCore.Qt.AlignBottom)
        self.navi_button_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.navi_button_2.setEnabled(True)
        self.navi_button_2.setAutoFillBackground(False)
        self.navi_button_2.setStyleSheet("background-color: transparent;")
        self.navi_button_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/kirins/icon/system/navigation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/kirins/icon/system/navigation_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.navi_button_2.setIcon(icon4)
        self.navi_button_2.setIconSize(QtCore.QSize(50, 50))
        self.navi_button_2.setCheckable(True)
        self.navi_button_2.setChecked(False)
        self.navi_button_2.setFlat(True)
        self.navi_button_2.setObjectName("navi_button_2")
        self.horizontalLayout_10.addWidget(self.navi_button_2, 0, QtCore.Qt.AlignBottom)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.up_button_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.up_button_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.up_button_4.setMouseTracking(True)
        self.up_button_4.setStyleSheet("background-color: transparent;")
        self.up_button_4.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/kirins/icon/system/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.up_button_4.setIcon(icon5)
        self.up_button_4.setIconSize(QtCore.QSize(30, 30))
        self.up_button_4.setFlat(True)
        self.up_button_4.setObjectName("up_button_4")
        self.gridLayout_2.addWidget(self.up_button_4, 0, 1, 1, 1)
        self.left_button_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.left_button_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.left_button_3.setMouseTracking(True)
        self.left_button_3.setStyleSheet("background-color: transparent;")
        self.left_button_3.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/kirins/icon/system/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_button_3.setIcon(icon6)
        self.left_button_3.setIconSize(QtCore.QSize(30, 30))
        self.left_button_3.setFlat(True)
        self.left_button_3.setObjectName("left_button_3")
        self.gridLayout_2.addWidget(self.left_button_3, 1, 0, 1, 1)
        self.home_button_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.home_button_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.home_button_3.setMouseTracking(True)
        self.home_button_3.setStyleSheet("background-color: transparent;")
        self.home_button_3.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/kirins/icon/system/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_button_3.setIcon(icon7)
        self.home_button_3.setIconSize(QtCore.QSize(30, 30))
        self.home_button_3.setFlat(True)
        self.home_button_3.setObjectName("home_button_3")
        self.gridLayout_2.addWidget(self.home_button_3, 1, 1, 1, 1)
        self.right_button_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.right_button_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.right_button_4.setMouseTracking(True)
        self.right_button_4.setStyleSheet("background-color: transparent;")
        self.right_button_4.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/kirins/icon/system/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right_button_4.setIcon(icon8)
        self.right_button_4.setIconSize(QtCore.QSize(30, 30))
        self.right_button_4.setFlat(True)
        self.right_button_4.setObjectName("right_button_4")
        self.gridLayout_2.addWidget(self.right_button_4, 1, 2, 1, 1)
        self.down_button_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.down_button_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.down_button_3.setMouseTracking(True)
        self.down_button_3.setStyleSheet("background-color: transparent;")
        self.down_button_3.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/kirins/icon/system/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.down_button_3.setIcon(icon9)
        self.down_button_3.setIconSize(QtCore.QSize(30, 30))
        self.down_button_3.setFlat(True)
        self.down_button_3.setObjectName("down_button_3")
        self.gridLayout_2.addWidget(self.down_button_3, 2, 1, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_2)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(600, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(204, 0, 0);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1160, 70, 111, 501))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.lock_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.lock_button_2.setEnabled(True)
        self.lock_button_2.setAutoFillBackground(False)
        self.lock_button_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/kirins/icon/system/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap(":/kirins/icon/system/lock_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.lock_button_2.setIcon(icon10)
        self.lock_button_2.setIconSize(QtCore.QSize(50, 50))
        self.lock_button_2.setCheckable(True)
        self.lock_button_2.setChecked(False)
        self.lock_button_2.setFlat(True)
        self.lock_button_2.setObjectName("lock_button_2")
        self.verticalLayout_8.addWidget(self.lock_button_2, 0, QtCore.Qt.AlignRight)
        self.syncgimbal_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.syncgimbal_button_2.setEnabled(True)
        self.syncgimbal_button_2.setAutoFillBackground(False)
        self.syncgimbal_button_2.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/kirins/icon/system/sync_gimbal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap(":/kirins/icon/system/syncgimbal_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.syncgimbal_button_2.setIcon(icon11)
        self.syncgimbal_button_2.setIconSize(QtCore.QSize(50, 50))
        self.syncgimbal_button_2.setCheckable(True)
        self.syncgimbal_button_2.setChecked(False)
        self.syncgimbal_button_2.setFlat(True)
        self.syncgimbal_button_2.setObjectName("syncgimbal_button_2")
        self.verticalLayout_8.addWidget(self.syncgimbal_button_2, 0, QtCore.Qt.AlignRight)
        self.angle_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.angle_button_2.setEnabled(True)
        self.angle_button_2.setAutoFillBackground(False)
        self.angle_button_2.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/kirins/icon/system/angle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap(":/kirins/icon/system/angle_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.angle_button_2.setIcon(icon12)
        self.angle_button_2.setIconSize(QtCore.QSize(50, 50))
        self.angle_button_2.setCheckable(True)
        self.angle_button_2.setChecked(False)
        self.angle_button_2.setFlat(True)
        self.angle_button_2.setObjectName("angle_button_2")
        self.verticalLayout_8.addWidget(self.angle_button_2, 0, QtCore.Qt.AlignRight)
        self.touch_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.touch_button_2.setEnabled(True)
        self.touch_button_2.setAutoFillBackground(False)
        self.touch_button_2.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/kirins/icon/system/touch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon13.addPixmap(QtGui.QPixmap(":/kirins/icon/system/touch_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.touch_button_2.setIcon(icon13)
        self.touch_button_2.setIconSize(QtCore.QSize(50, 50))
        self.touch_button_2.setCheckable(True)
        self.touch_button_2.setChecked(False)
        self.touch_button_2.setFlat(True)
        self.touch_button_2.setObjectName("touch_button_2")
        self.verticalLayout_8.addWidget(self.touch_button_2, 0, QtCore.Qt.AlignRight)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.layoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_5.setGeometry(QtCore.QRect(1010, 10, 265, 58))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.reset_button_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.reset_button_2.setEnabled(True)
        self.reset_button_2.setAutoFillBackground(False)
        self.reset_button_2.setStyleSheet("")
        self.reset_button_2.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/kirins/icon/system/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset_button_2.setIcon(icon14)
        self.reset_button_2.setIconSize(QtCore.QSize(50, 50))
        self.reset_button_2.setCheckable(False)
        self.reset_button_2.setChecked(False)
        self.reset_button_2.setFlat(True)
        self.reset_button_2.setObjectName("reset_button_2")
        self.horizontalLayout_11.addWidget(self.reset_button_2)
        self.focus_button_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.focus_button_2.setEnabled(True)
        self.focus_button_2.setAutoFillBackground(False)
        self.focus_button_2.setStyleSheet("")
        self.focus_button_2.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/kirins/icon/system/focus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon15.addPixmap(QtGui.QPixmap(":/kirins/icon/system/focus_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.focus_button_2.setIcon(icon15)
        self.focus_button_2.setIconSize(QtCore.QSize(50, 50))
        self.focus_button_2.setCheckable(True)
        self.focus_button_2.setChecked(False)
        self.focus_button_2.setFlat(True)
        self.focus_button_2.setObjectName("focus_button_2")
        self.horizontalLayout_11.addWidget(self.focus_button_2)
        self.EPS_button_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.EPS_button_2.setEnabled(True)
        self.EPS_button_2.setAutoFillBackground(False)
        self.EPS_button_2.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/kirins/icon/system/EPS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon16.addPixmap(QtGui.QPixmap(":/kirins/icon/system/eps_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.EPS_button_2.setIcon(icon16)
        self.EPS_button_2.setIconSize(QtCore.QSize(50, 50))
        self.EPS_button_2.setCheckable(True)
        self.EPS_button_2.setChecked(False)
        self.EPS_button_2.setFlat(True)
        self.EPS_button_2.setObjectName("EPS_button_2")
        self.horizontalLayout_11.addWidget(self.EPS_button_2)
        self.setting_button_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.setting_button_2.setEnabled(True)
        self.setting_button_2.setAutoFillBackground(False)
        self.setting_button_2.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/kirins/icon/system/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon17.addPixmap(QtGui.QPixmap(":/kirins/icon/system/setting_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.setting_button_2.setIcon(icon17)
        self.setting_button_2.setIconSize(QtCore.QSize(50, 50))
        self.setting_button_2.setCheckable(True)
        self.setting_button_2.setChecked(False)
        self.setting_button_2.setFlat(True)
        self.setting_button_2.setObjectName("setting_button_2")
        self.horizontalLayout_11.addWidget(self.setting_button_2)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(560, 290, 181, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.progressBar_2 = QtWidgets.QProgressBar(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.progressBar_2.setProperty("value", 5)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout_2.addWidget(self.progressBar_2)
        self.zoom_widget = QtWidgets.QWidget(self.frame)
        self.zoom_widget.setGeometry(QtCore.QRect(1050, 110, 91, 411))
        self.zoom_widget.setObjectName("zoom_widget")
        self.zoom_out_2 = QtWidgets.QLabel(self.zoom_widget)
        self.zoom_out_2.setGeometry(QtCore.QRect(37, 38, 15, 15))
        self.zoom_out_2.setText("")
        self.zoom_out_2.setPixmap(QtGui.QPixmap(":/kirins/icon/system/plus.png"))
        self.zoom_out_2.setScaledContents(True)
        self.zoom_out_2.setObjectName("zoom_out_2")
        self.zoom_bar_2 = QtWidgets.QSlider(self.zoom_widget)
        self.zoom_bar_2.setGeometry(QtCore.QRect(40, 60, 20, 291))
        self.zoom_bar_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.zoom_bar_2.setMaximum(31)
        self.zoom_bar_2.setProperty("value", 1)
        self.zoom_bar_2.setOrientation(QtCore.Qt.Vertical)
        self.zoom_bar_2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.zoom_bar_2.setTickInterval(0)
        self.zoom_bar_2.setObjectName("zoom_bar_2")
        self.zoom_in_2 = QtWidgets.QLabel(self.zoom_widget)
        self.zoom_in_2.setGeometry(QtCore.QRect(38, 354, 15, 15))
        self.zoom_in_2.setText("")
        self.zoom_in_2.setPixmap(QtGui.QPixmap(":/kirins/icon/system/minus.png"))
        self.zoom_in_2.setScaledContents(True)
        self.zoom_in_2.setObjectName("zoom_in_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.zoom_widget)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 370, 61, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.layoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 10, 399, 58))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.infer_button_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.infer_button_2.setEnabled(True)
        self.infer_button_2.setAutoFillBackground(False)
        self.infer_button_2.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/kirins/icon/system/infer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon18.addPixmap(QtGui.QPixmap(":/kirins/icon/system/infer.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.infer_button_2.setIcon(icon18)
        self.infer_button_2.setIconSize(QtCore.QSize(50, 50))
        self.infer_button_2.setCheckable(True)
        self.infer_button_2.setChecked(False)
        self.infer_button_2.setFlat(True)
        self.infer_button_2.setObjectName("infer_button_2")
        self.horizontalLayout_12.addWidget(self.infer_button_2)
        self.MOT_button_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.MOT_button_2.setEnabled(True)
        self.MOT_button_2.setAutoFillBackground(False)
        self.MOT_button_2.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/kirins/icon/system/MOT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon19.addPixmap(QtGui.QPixmap(":/kirins/icon/system/MOT.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.MOT_button_2.setIcon(icon19)
        self.MOT_button_2.setIconSize(QtCore.QSize(50, 50))
        self.MOT_button_2.setCheckable(True)
        self.MOT_button_2.setChecked(False)
        self.MOT_button_2.setFlat(True)
        self.MOT_button_2.setObjectName("MOT_button_2")
        self.horizontalLayout_12.addWidget(self.MOT_button_2)
        self.SOT_button_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.SOT_button_2.setEnabled(True)
        self.SOT_button_2.setAutoFillBackground(False)
        self.SOT_button_2.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/kirins/icon/system/SOT.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon20.addPixmap(QtGui.QPixmap(":/kirins/icon/system/SOT_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.SOT_button_2.setIcon(icon20)
        self.SOT_button_2.setIconSize(QtCore.QSize(50, 50))
        self.SOT_button_2.setCheckable(True)
        self.SOT_button_2.setChecked(False)
        self.SOT_button_2.setFlat(True)
        self.SOT_button_2.setObjectName("SOT_button_2")
        self.horizontalLayout_12.addWidget(self.SOT_button_2)
        self.syncbbox_button_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.syncbbox_button_2.setEnabled(True)
        self.syncbbox_button_2.setAutoFillBackground(False)
        self.syncbbox_button_2.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/kirins/icon/system/sync_bbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon21.addPixmap(QtGui.QPixmap(":/kirins/icon/system/sync_bbox_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.syncbbox_button_2.setIcon(icon21)
        self.syncbbox_button_2.setIconSize(QtCore.QSize(50, 50))
        self.syncbbox_button_2.setCheckable(True)
        self.syncbbox_button_2.setChecked(False)
        self.syncbbox_button_2.setFlat(True)
        self.syncbbox_button_2.setObjectName("syncbbox_button_2")
        self.horizontalLayout_12.addWidget(self.syncbbox_button_2)
        self.inspection_button_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.inspection_button_2.setEnabled(True)
        self.inspection_button_2.setAutoFillBackground(False)
        self.inspection_button_2.setStyleSheet("")
        self.inspection_button_2.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/kirins/icon/system/inspection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon22.addPixmap(QtGui.QPixmap(":/kirins/icon/system/inspection_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.inspection_button_2.setIcon(icon22)
        self.inspection_button_2.setIconSize(QtCore.QSize(50, 50))
        self.inspection_button_2.setCheckable(True)
        self.inspection_button_2.setChecked(False)
        self.inspection_button_2.setFlat(True)
        self.inspection_button_2.setObjectName("inspection_button_2")
        self.horizontalLayout_12.addWidget(self.inspection_button_2)
        self.laser_button_2 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.laser_button_2.setEnabled(True)
        self.laser_button_2.setAutoFillBackground(False)
        self.laser_button_2.setStyleSheet("")
        self.laser_button_2.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/kirins/icon/system/laser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon23.addPixmap(QtGui.QPixmap(":/kirins/icon/system/laser_.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.laser_button_2.setIcon(icon23)
        self.laser_button_2.setIconSize(QtCore.QSize(50, 50))
        self.laser_button_2.setCheckable(True)
        self.laser_button_2.setChecked(False)
        self.laser_button_2.setFlat(True)
        self.laser_button_2.setObjectName("laser_button_2")
        self.horizontalLayout_12.addWidget(self.laser_button_2)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1280, 50))
        self.frame_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(1120, 10, 141, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(20, 5, 49, 40))
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/kirins/icon/system/logo_white.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RNG_value_2.setText(_translate("MainWindow", "60 m"))
        self.LON_value_2.setText(_translate("MainWindow", "LON"))
        self.ASL_2.setText(_translate("MainWindow", "ASL"))
        self.RNG_2.setText(_translate("MainWindow", "RNG"))
        self.ASL_value_2.setText(_translate("MainWindow", "1 m"))
        self.LAT_value_2.setText(_translate("MainWindow", "LAT"))
        self.label_2.setText(_translate("MainWindow", "Searching..."))
        self.label_3.setText(_translate("MainWindow", "Successfully loaded"))
        self.checkBox_2.setText(_translate("MainWindow", "Auto"))
        self.label_4.setText(_translate("MainWindow", "Hera View"))
import resource_rc
